<?php

if ( !defined( 'ABSPATH' ) ) {
    exit;
}
function ai_moderator_for_buddypress( $activity )
{
    $content = $activity->content;
    // Get the list of prohibited words from the plugin settings
    $prohibited_words = get_option( 'ai_moderator_for_buddypress_prohibited_words' );
    // Check if the content contains any of the prohibited words
    $response = null;
    $contains_prohibited_word = false;
    foreach ( $prohibited_words as $word ) {
        
        if ( strpos( strtolower( $content ), strtolower( $word ) ) !== false ) {
            $contains_prohibited_word = true;
            break;
        }
    
    }
    // If the content contains a prohibited word, send an OpenAI API request to check if it is spam
    
    if ( !$contains_prohibited_word ) {
        $openai_api_key = get_option( 'ai_moderator_for_buddypress_openai_api_key' );
        // Send the content to the OpenAI API for analysis
        $response = wp_remote_post( 'https://api.openai.com/v1/completions', array(
            'headers' => array(
            'Content-Type'  => 'application/json',
            'Authorization' => 'Bearer ' . $openai_api_key,
        ),
            'body'    => json_encode( array(
            'model'       => 'text-babbage-001',
            'prompt'      => 'Someone posted an activity post in my site. Please check if the below activity content is spam or not. If you think its spam, only reply with Yes or No. The content is: ' . $content,
            'temperature' => 0.5,
        ) ),
        ) );
        
        if ( isset( $response['body'] ) ) {
            $response_body = json_decode( $response['body'], true );
            
            if ( isset( $response_body['error'] ) ) {
                $api_error_message = $response_body['error']['message'];
                $admin_email = get_option( 'admin_email' );
                // Get the admin email address
                $subject = 'ERROR MODERATING ACTIVITY POSTS';
                // Set the email subject
                $message = 'This email was auto-generated by "AI Moderator for Buddypress and BuddyBoss" plugin. One of your Activity Feed\' post couldn\'t be sent for moderation to OPEN AI. We recieved the below error from OPEN AI\'s API endpoint when we were trying to send a request: "' . $api_error_message . '"';
                // Set the email message
                wp_mail( $admin_email, $subject, $message );
                // Send the email
            }
        
        }
    
    }
    
    // If the OpenAI API response indicates that the content is spam, mark the activity post as spam and send a notification to the user
    
    if ( $contains_prohibited_word || !is_wp_error( $response ) && isset( $response['body'] ) && strpos( $response['body'], 'Yes' ) !== false ) {
        $activity->is_spam = 1;
        $activity->save();
        // Get the user who created the activity
        $user_id = $activity->user_id;
        // Add the notification to the user
        bp_notifications_add_notification( array(
            'user_id'          => $user_id,
            'item_id'          => $activity->id,
            'component_name'   => 'ai_buddyboss_notifications',
            'component_action' => 'ai_buddyboss_notifications',
            'date_notified'    => bp_core_current_time(),
            'is_new'           => 1,
            'allow_duplicate'  => true,
        ) );
    }

}

add_action(
    'ai_moderator_check',
    'ai_moderator_for_buddypress',
    10,
    1
);